### ISSUE TITLE
Can I use it to suit 10.14 with NV1060?

### ISSUE THREAD

**Issue by MichaelVector** [corpnewt/Web-Driver-Toolkit#1]
I just update from 17G65(10.13.6) to 17G3025(10.13.6).
The tool worked fine. (Not with this tool , NVdriver can't install in 17G3025).
So I think ,can I update to 10.14 and install driver with 10.13.6(modify by this tool from 17G65 to 10.14)?

**Comment by MichaelVector** [comment]
nVida 1060 3G Card

**Comment by corpnewt** [comment]
`The tool worked fine. (Not with this tool , NVdriver can't install in 17G3025).`

This tool can patch both the install pkg and the installed kext - so it could get the web drivers working on the latest build of 10.13.6 without issue.  The 10.13.6 web drivers themselves though, even if patched to *load* on 10.14, won't work correctly on Mojave as that OS has a different graphics api and requires more than just the target build version changed for acceleration.  So, you may get full res, and possible multi-monitor support, but everything will still be software rendered.
