### ISSUE TITLE
can't decode byte 0x9a

### ISSUE THREAD

**Issue by phhoef** [corpnewt/Web-Driver-Toolkit#3]
Hi,

i just installed the latest update for macOS High Sierra (10.13.6).
As I am using Nvidia GTX1080 graphics card, I had installed Nvidia WebDriver.
After the update the WebDriver was no longer compatible with macOS version.

That's why I used this app to patch the version.
When executing the `Run.Command` the following error occurs:
``` 
 ##################################################
 #              Web Driver Toolkit                #
##################################################
 
OS Version:       10.13.6 - 17G4015
WD Version:       387.10.10.10.40.108
WD Target Build:  17G4015
Newest:           None for this build number!
'utf8' codec can't decode byte 0x9a in position 756: invalid start byte
```

I tracked the problem down. In the `bdmesg.py` file on line 34, the result of the subprocess is decoded with UTF-8.
```
   # Runs ioreg -l -p IODeviceTree -w0 and searches for "boot-log"
    p = subprocess.Popen(comm, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    bd, be = p.communicate()

    for line in bd.decode("utf-8").split("\n"):
        # We're just looking for the "boot-log" property, then we need to format it
        if not '"boot-log"' in line:
            # Skip it!
            continue
```

After removing the `decode("utf-8")`, the script works as expected.
I am not sure, if this problem occurs for every hackintosh or just for me.

**Comment by corpnewt** [comment]
Looks like there's some special chars in your boot-log that utf-8 can't decode. Can you run `ioreg -l -p IODeviceTree -w0 | grep -i "boot-log" > ~/Desktop/bdmesg.txt` in terminal and send the resulting bdmesg.txt file on your Desktop?

**Comment by phhoef** [comment]
sure, please find the file attached.
[bdmesg.txt](https://github.com/corpnewt/Web-Driver-Toolkit/files/2658013/bdmesg.txt)

**Comment by corpnewt** [comment]
So - I tried storing that same char (0x9a) "Ě" in a text file (called text.txt on my desktop), and `cat`ing its contents via both python 2 and python 3, then decoding and printing it.  The script used is as follows:
```py
import subprocess as s

p = s.Popen(["cat","text.txt"], shell=False, stdout=s.PIPE, stderr=s.PIPE)
o,e = p.communicate()
print(type(o), o)
print(type(e), e)

print(o.decode("utf-8"))
```
My hope was to recreate the error you are having above by causing some subprocess to spit out a character that's not terribly friendly with utf-8 and see if I could print and decode it.
The output is as follows:
```
CorpNewt's iHack:desktop corp$ python3 /Users/corp/Desktop/test.py 
<class 'bytes'> b'\xc4\x9a'
<class 'bytes'> b''
Ě
CorpNewt's iHack:desktop corp$ python /Users/corp/Desktop/test.py 
(<type 'str'>, '\xc4\x9a')
(<type 'str'>, '')
Ě
```
Would you mind testing the same process to see if that fails as well?  If it doesn't - could you dump your whole ioreg via the following and send it `ioreg -l -p IODeviceTree -w0 > ~/Desktop/ioreg.txt`?

Attached is the text doc I used - github does not allow me to send .py files - but the code is above in the first code block.

[text.txt](https://github.com/corpnewt/Web-Driver-Toolkit/files/2658116/text.txt)

- CorpNewt

**Comment by phhoef** [comment]
I do not have python 3 installed.
```
python --version
Python 2.7.10
```

I executed your test script and placed the test.txt next to it.
The following output seems to match with yours:
```
./test.py 
(<type 'str'>, '\xc4\x9a')
(<type 'str'>, '')
Ě
```

As it does not fail, I've attached the ioreg.txt file.

Thanks
[ioreg.txt](https://github.com/corpnewt/Web-Driver-Toolkit/files/2658216/ioreg.txt)

**Comment by corpnewt** [comment]
Thanks for helping me debug this - I'll give the ioreg.txt file a look and see what I can figure out.  Hopefully I'll have more tests to run (or even better, a solution) shortly!

-CorpNewt

**Comment by phhoef** [comment]
No problem :-) Thanks for providing this script. Saved my day more than once!
If I can help you, don't hesitate to ask ...

**Comment by corpnewt** [comment]
I just pushed a small update to the bdmesg.py file that should only attempt to decode the output if running py3, and the output type is bytes.  Hopefully that fixes the issue.  If it works, I'll update that module (and a few other things) on my other repos as well.

**Comment by phhoef** [comment]
Yes, indeed.
I just cloned this repository again to catch the latest changes.
When executing the `Run.Command` the version information about OS etc are shown and also the menu.
It seems that this fixed the problem. Thanks

**Comment by corpnewt** [comment]
Sounds good - I'll push the changes to my other repos and close this issue.
Thanks for your patience!

-CorpNewt
