### ISSUE TITLE
Retrieving Manifest Issue - "Manifest not available!"

### ISSUE THREAD

**Issue by aldaff** [corpnewt/Web-Driver-Toolkit#5]
##################################################
 #            Retrieving Manifest...              #
##################################################
 
Retrieving manifest from "https://gfe.nvidia.com/mac-update"...

Something went wrong while getting the manifest!

Please check your intenet connection and try again.

_Then, it loads and I get:_

  ##################################################
 #              Web Driver Toolkit                #
##################################################
 
OS Version:       10.13.6 - 17G4015
WD Version:       387.10.10.10.40.113
WD Target Build:  17G4015
**Newest:           Manifest not available!**

**Comment by corpnewt** [comment]
```
  ##################################################
 #              Web Driver Toolkit                #
##################################################
 
OS Version:       10.12.6 - 16G1710
WD Version:       378.05.05.25f12
WD Target Build:  16G1710
Newest:           378.05.05.25f12 (Current)
Status:           Enabled (AptioMemoryFix Loaded)
 
P. Patch Menu
I. Patch Install Package
D. Download For Current
B. Download By Build Number
S. Search By Build/OS Number
R. Remove Web Drivers
U. Update Manifest
C. Config.plist Patch Menu
F. Flush Kext Cache
N. Attempt to unset nvram_drv=1 in NVRAM

Q. Quit
 
Please make a selection (just press enter to reload):
```
I just opened it on my machine and it seems to work fine.  Might be an issue with your connection?

**Comment by aldaff** [comment]
Strange. I can't see anything blocking it. I watched LittleSnitch allow the terminal connection, so not sure what the issue could be.
![image](https://user-images.githubusercontent.com/33010926/51290217-4f836980-1a57-11e9-89a9-513d0ef062c1.png)

**Comment by aldaff** [comment]
I just added a print statement for plist_data in the WebDriver.py file, in the except clause of the get_manifest function.
![image](https://user-images.githubusercontent.com/33010926/51291027-d8030980-1a59-11e9-87d0-4060bb7b32d5.png)

**Comment by aldaff** [comment]
I just added a print statement for plist_data in the WebDriver.py file, in the except clause of the get_manifest function. 
![image](https://user-images.githubusercontent.com/33010926/51292074-a8ee9700-1a5d-11e9-851a-ce4a2ae2c16f.png)

![image](https://user-images.githubusercontent.com/33010926/51292067-a12ef280-1a5d-11e9-9c1a-b0eb5bc3d5bd.png)

Seems it could be an SSL cert verification error?

**Comment by aldaff** [comment]
Not sure if you changed anything, but I installed Python 2.7 (previously only had 3.6 & 3.7 installed) and it is now working.
When running WebDriver.py with Python 2.7 it all works fine, but when running with Python 3.7 there is a DeprecationWarning:
![screen shot 2019-01-21 at 11 49 57 am](https://user-images.githubusercontent.com/33010926/51447478-b1531480-1d72-11e9-9b06-e6e1c4ab9138.png)
The program still works, however.
