### ISSUE TITLE
Do we need to patch the installed web drivers as well?

### ISSUE THREAD

**Issue by madmax2** [corpnewt/Web-Driver-Toolkit#6]
Once we patch the install driver package
we can bypass the check and install the driver

Now do we need to again run the script and patch the newly installed driver as well?

And is there any restarts required first?

**Comment by corpnewt** [comment]
I apologize for the delay in responding to this;

If you patched both the package and the kext in the first step, you don't need to re-patch the kext after installing.

There are 2 checks in the web drivers; one in the .pkg that determines whether or not it can be installed, and one in the actual NVDAStartupWeb.kext that determines whether it will activate.  The script offers to patch both when you patch the .pkg - but what you selected determines what happened.

You will need to restart for changes to the kext to take effect, yes.

As this is not an issue with the script, I'm going to close this issue - but feel free to respond here if you have other questions.

-CorpNewt
