### ISSUE TITLE
Mojave 10.14.6 on MBP boot failed after disable SIP and installed the patched Webdriver

### ISSUE THREAD

**Issue by xmurobi** [corpnewt/Web-Driver-Toolkit#9]
I try couples of ways to install the patched webdrive, including:
1) Use two versions of driver:
10.13.6 (17G7024)	and 10.13.6 (17G8030)
2) `csrutil disable` in safe mode before install.
3) `spctl kext-consent add 6KR3T733EC` in safe mode before install.

But all this tries are failed after patched driver install & reboot. macOS stuck at white apple screen with progress bar almost at 75%.

I used verbose mode to check booting progress and got:

![IMG_6786](https://user-images.githubusercontent.com/1903164/64916537-7eeaa180-d7b1-11e9-96a9-e02eedb4acc1.JPG)

Looks the driver not found system API in Mojave 10.14.6?

Could you help on this issue? @corpnewt 

BTW, my MBP with NVIDIA GTX 650M Graphics card.

**Comment by corpnewt** [comment]
Looks like the symbols called in the Web Drivers don't resolve to anything - so even patching them to load on whatever build number won't help.  The Web Driver Toolkit's patching approach can't do anything about that - as all it does is work around the build check.

Regardless, this isn't an issue with the script itself - Mojave and Catalina aren't likely to get any Nvidia love from Apple any time soon (if ever).

-CorpNewt
